server:
  port: 8082

spring:
  application:
    name: orders

  datasource:
    url: jdbc:postgresql://localhost:5432/db_orders
    username: admin
    password: admin
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    hostname: orders

catalogue:
  url: ${CATALOGUE_URL:http://catalogue/api/v1}
